[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "test_ajd"
version = "0.0.1"
dependencies = [
  "pandas",
  "click",
  "typing",
  "json",
]
requires-python = ">=3.10"