[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.10"
name = "mydummy"
version = "0.0.1" 
description = "tester"
readme = "README.md"
dependencies=[
    "pandas"
    "click"
]